version: 2

models:
  - name: fact_employer_hiring
    description: "Fact table for job postings and hires"
    columns:
      - name: Job_ID
        description: "Unique job identifier"
        tests: [not_null, unique]
      - name: Company_Name
        description: "Hiring company"
      - name: Job_Title
        description: "Title of the job"
      - name: Applications_Received
        description: "Number of applications received"
      - name: Hires_Made
        description: "Number of hires made"

  - name: dim_employer
    description: "Companies and locations"
    columns:
      - name: Company_Name
        description: "Employer name"
      - name: Job_Location
        description: "Location of job posting"

  - name: dim_job
    description: "Job details and employment types"
    columns:
      - name: Job_Title
        description: "Job title"
      - name: Employment_Type
        description: "Full-time, Part-time, etc."

  - name: dim_skill
    description: "Skills required for job roles"
    columns:
      - name: Required_Skills
        description: "Comma-separated list of skills"

  - name: dim_employment_type
    description: "Normalized employment types"
    columns:
      - name: Employment_Type
        description: "Type of employment"

  - name: dim_location
    description: "Unique job locations"
    columns:
      - name: Job_Location
        description: "Geographic location"