version: 2

models:
  - name: dim_time
    description: "Centralized time dimension used across all star schemas"
    columns:
      - name: date_key
        description: "Date key"
        tests: [not_null]
