version: 2

models:
  - name: fact_platform_performance
    description: "Platform activity and performance metrics"
    columns:
      - name: date_key
        description: "Surrogate key from dim_time"
        tests: [not_null]
      - name: active_users
        description: "Daily active users"
      - name: platform_crashes
        description: "Count of platform crashes"

  - name: dim_platform
    description: "Mobile or web platform"
    columns:
      - name: platform_type
        description: "Mobile or Web"

  - name: dim_crash_type
    description: "Crash reasons and categories (optional)"
    columns:
      - name: platform_crashes
        description: "Crash identifier or type"
