version: 2

models:
  - name: fact_platform_performance
    description: "Platform activity and performance metrics"
    columns:
      - name: date_key
        description: "Surrogate key from dim_time"
        tests: [not_null]
      - name: active_users
        description: "Daily active users"
      - name: platform_crashes
        description: "Count of platform crashes"

  - name: dim_platform
    description: "Mobile or web platform dimension"
    columns:
      - name: platform_type
        description: "Indicates whether the user accessed the platform via mobile or web"
        tests: [not_null]

  - name: dim_crash_type
    description: "Crash reasons and severity labels"
    columns:
      - name: crash_key
        description: "Crash severity level as a key (0–4)"
        tests: [not_null, unique]
      - name: crash_type
        description: "Crash severity label (e.g., None, Minor, Moderate, Critical)"

  - name: dim_user_engagement
    description: "User engagement level based on active users"
    columns:
      - name: active_users
        description: "Number of active users for a given day"
        tests: [not_null]
      - name: engagement_level
        description: "Engagement category (Low, Medium, High)"
        tests: [not_null]
